name: Reusable Workflow

on:
  workflow_call:
    inputs:
      projeto:
        type: string
        required: true

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Projeto - ${{ inputs.projeto }}"