name: Reusable Workflow

on:
  workflow_call:
    inputs:
      projeto:
        type: string
        required: true
      ambiente:
        type: string
        required: true
        

    outputs:
      resultado:
        description: "Resultado da execução"
        value: ${{ jobs.exemplo.outputs.resultado }}

jobs:
  exemplo:
    runs-on: ubuntu-latest

    outputs:
      resultado: ${{ steps.resultado.outputs.mensagem }}

    steps:
      - id: resultado
        run: echo "mensagem=Pipeline executada com sucesso" >> "$GITHUB_OUTPUT"

      - run: echo "Projeto - ${{ inputs.projeto }}"

      - run: echo "Ambiente - ${{ inputs.ambiente }}"